<a href="https://colab.research.google.com/github/ArpanChaudhary/Pandas/blob/main/pandas5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## PANDAS

In [1]:
## Import pandas and NumPy libraries

In [2]:
import numpy as np
import pandas as pd

## Data Manipulation

In [3]:
df = pd.read_csv('/content/titanic_train.csv')

In [4]:
df.head()

,Unnamed: 0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

## How to check the unique values of any column

In [5]:
df['Survived'].unique()

array([0, 1])

## How to rename categories using pandas

In [6]:
new_survived = pd.Categorical(df['Survived'])

new_survived = new_survived.rename_categories(['Died','Survived'])

new_survived.describe()

            counts     freqs
categories
Died           549  0.616162
Survived       342  0.383838

In [7]:
df['Pclass'].unique()

array([3, 1, 2])

In [8]:
new_Pclass = pd.Categorical(df['Pclass'])

new_Pclass = new_Pclass.rename_categories(['Class1','Class2','Class3'])

new_Pclass.describe()

            counts     freqs
categories
Class1         216  0.242424
Class2         184  0.206510
Class3         491  0.551066

In [9]:
## re-assigning the column 'Pclass' with new values

In [10]:
df['Pclass'] = new_Pclass

In [11]:
df

,Unnamed: 0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,1,0,Class3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,2,1,Class1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,2,3,1,Class3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,3,4,1,Class1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,4,5,0,Class3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,886,887,0,Class2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,887,888,1,Class1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,888,889,0,Class3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,889,890,1,Class1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,890,891,0,Class3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [12]:
# Let's check for the age missing

In [13]:
df['Age'].isna().sum()

177

In [14]:
age_missing = df[~df.Age.isin(['NaN'])]

age_missing

,Unnamed: 0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,1,0,Class3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,2,1,Class1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,2,3,1,Class3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,3,4,1,Class1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,4,5,0,Class3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,886,887,0,Class2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,887,888,1,Class1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,888,889,0,Class3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,889,890,1,Class1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,890,891,0,Class3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

## Find the maximum fare

In [15]:
maximum_fare = df[df.Fare.isin([max(df['Fare'])])]

maximum_fare

,Unnamed: 0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
258,258,259,1,Class1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,NaN,C
679,679,680,1,Class1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C
737,737,738,1,Class1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C

## Find the minimum fare

In [16]:
minimum_fare = df[df.Fare.isin([min(df['Fare'])])]

minimum_fare

,Unnamed: 0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
179,179,180,0,Class3,"Leonard, Mr. Lionel",male,36.0,0,0,LINE,0.0,NaN,S
263,263,264,0,Class1,"Harrison, Mr. William",male,40.0,0,0,112059,0.0,B94,S
271,271,272,1,Class3,"Tornquist, Mr. William Henry",male,25.0,0,0,LINE,0.0,NaN,S
277,277,278,0,Class2,"Parkes, Mr. Francis ""Frank""",male,NaN,0,0,239853,0.0,NaN,S
302,302,303,0,Class3,"Johnson, Mr. William Cahoone Jr",male,19.0,0,0,LINE,0.0,NaN,S
413,413,414,0,Class2,"Cunningham, Mr. Alfred Fleming",male,NaN,0,0,239853,0.0,NaN,S
466,466,467,0,Class2,"Campbell, Mr. William",male,NaN,0,0,239853,0.0,NaN,S
481,481,482,0,Class2,"Frost, Mr. Anthony Wood ""Archie""",male,NaN,0,0,239854,0.0,NaN,S
597,597,598,0,Class3,"Johnson, Mr. Alfred",male,49.0,0,0,LINE,0.0,NaN,S
633,633,634,0,Class1,"Parr, Mr. William Henry Marsh",male,NaN,0,0,112052,0.0,NaN,S
674,674,675,0,Class2,"Watson, Mr. Ennis Hastings",male,NaN,0,0,239856,0.0,NaN,S
732,732,733,0,Class2,"Knight, Mr. Robert J",male,NaN,0,0,239855,0.0,NaN,S
806,806,807,0,Class1,"Andrews, Mr. Thomas Jr",male,39.0,0,0,112050,0.0,A36,S
815,815,816,0,Class1,"Fry, Mr. Richard",male,NaN,0,0,112058,0.0,B102,S
822,822,823,0,Class1,"Reuchlin, Jonkheer. John George",male,38.0,0,0,19972,0.0,NaN,S